symfonycasts_tailwind:
    binary_version: 'v4.0.2'
    # input_css ==> set the tailwind entry point to be built
    # ATTN: accepts only 1 tailwind entry point !
    # There is a PR for accepting multiplt entry points, but I could not get it to work
    # https://github.com/SymfonyCasts/tailwind-bundle/issues/46
    # https://github.com/SymfonyCasts/tailwind-bundle/pull/58
    # We would have liked to build also admin.css with tailwind
    # which would allow us to import css files from admin.css 
    # but since it's not working, we DO NOT build admin.css with tailwind
    # thus we do all css imports in admin.js (handled by asset mapper), not in admin.css
    input_css: 'assets/styles/app.css'
